name: Dockerized Unit Tests

on:
  push:
    branches: [ documentacion ]
  pull_request:
    branches: [ documentacion ]

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image (with devDeps)
        run: |
          docker build \
            --build-arg INSTALL_DEV=true \
            -t todo-api:test \
            -f Dockerfile .

      - name: Run unit tests inside container
        run: |
          docker run --rm todo-api:test \
            sh -c "./node_modules/.bin/jest --coverage"